### PR TITLE
Add support for `packages` entry point strategy

### PR DESCRIPTION
**Pull request by HiDeoo**

### CODE REVIEW

**Review by boneskull — APPROVED** [review]
This builds successfully for me.  I haven't tried to customize the sidebar yet.

I do see some unstyled markdown coming through, but I'm not sure if that's `typedoc-plugin-markdown`'s fault or no.

image

**Comment by boneskull** [comment]
Also I'm seeing an empty "References" section.

**Comment by boneskull** [comment]
Note: `StarlightTypeDocOptions.watch` should be broken with the `packages` strategy if you are using TypeDoc's own "watch" facilities (looks like this is the case).

**Comment by boneskull** [comment]
The reflections generated by [`outputFileStrategy: 'modules'`](https://www.typedoc-plugin-markdown.org/options#outputfilestrategy) don't seem to be well-understood by the sidebar-generation code.  From what I can tell, there's no such `ReflectionGroup` where `.title = 'Modules'`, so the recursion in `getSidebarGroupFromReflections()` isn't occurring.

**Comment by HiDeoo** [comment]
Thanks for the valuable feedback. To address the various points:

> I do see some unstyled invalid markdown (extra whitespace) coming through, but I'm not sure if that's typedoc-plugin-markdown's fault or no.

As you pointed out, this is indeed due to the extra spaces and this is the expected behavior according to the [spec](https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis) regarding delimiter run:

> A left-flanking delimiter run is a delimiter run that is (1) not followed by Unicode whitespace

---

> Also I'm seeing an empty "References" section.

This should now be fixed:

SCR-20240104-ocuh

---

> Note: `StarlightTypeDocOptions.watch` should be broken with the `packages` strategy if you are using TypeDoc's own "watch" facilities (looks like this is the case).

There is an [issue](https://github.com/TypeStrong/typedoc/issues/1772) for this in the TypeDoc repository so not much I can do about it from my side.

Maybe I should add a note about this in the documentation?

---

> The reflections generated by [`outputFileStrategy: 'modules'`](https://www.typedoc-plugin-markdown.org/options#outputfilestrategy) don't seem to be well-understood by the sidebar-generation code.

Yeah, this is one entry in my notes regarding that plugin which is not properly handled yet and may require some thinking to get it right. This is not a strategy I use myself but last time I encountered it, I was having issue with the markdown plugin like you mentioned. Once fixed, I think an approach could be in this specific case to no longer rely on Starlight `autogenerate` and manually constructing the sidebar but that's only my first thought.

**Comment by boneskull** [comment]
re: watch mode, seems like it might be possible get the list of source files out of TypeDoc, then use [addWatchFile](https://docs.astro.build/en/reference/integrations-reference/#addwatchfile-option) on each.  I don't think TypeDoc has any sort of incremental build, so you'll have to restart it from scratch every time anyway.  in theory, a viable workaround, but idk if there are any unintended consequences...

**Comment by boneskull** [comment]
Anyway, thanks for your work on this!

**Pull request merged**
